### ISSUE TITLE
SasFileReaderImpl hangs in endless loop

### ISSUE THREAD

**Issue by marco-boeck** [epam/parso#13]
Providing a certain, invalid SAS InputStream to the SasFileReaderImpl(InputStream) constructor will create an endless loop in SasFileParser#306:

    while (actuallySkipped < bytesLeft) {
        actuallySkipped += sasFileStream.skip(bytesLeft - actuallySkipped);
    }
As per JavaDoc of `FilterInputStream.skip(long n)`, skip may skip less than asked, down to 0 bytes. This is the case here which means the loop is never exited.

Tested with the following code:

    // this file has been deleted so we get the 404 page as InputStream
    URL url = new URL("http://www.bus.utk.edu/stat/Stat579/beef.sas7bdat");
    URLConnection connection = url.openConnection();
    SasFileReaderImpl sasFileReader = new SasFileReaderImpl(connection.getInputStream());

**Comment by PetrTsurinov** [comment]
Updated code and fixed issue. Please write if you need new version release.

**Comment by marco-boeck** [comment]
@PetrTsurinov Yes please, a new version would be much appreciated :)

**Comment by Petr1990** [comment]
@marco-boeck We released version 2.0.3, please try it. You are welcome.

**Comment by PetrTsurinov** [comment]
@marco-boeck We released version 2.0.3, please try it. You are welcome.

**Comment by marco-boeck** [comment]
@PetrTsurinov Works like a charm, thanks again!
