### ISSUE TITLE
Parso failed to parse SAS file with none seekable binary channel

### ISSUE THREAD

**Issue by ruiwanguk** [epam/parso#17]
When the input stream feeds into the parso library is ChannelInputStream, the available() method sometimes returns 0 when the Channel is not a SeekableByteChannel.

` public int available() throws IOException {
        if(this.ch instanceof SeekableByteChannel) {
            SeekableByteChannel var1 = (SeekableByteChannel)this.ch;
            long var2 = Math.max(0L, var1.size() - var1.position());
            return var2 > 2147483647L?2147483647:(int)var2;
        } else {
            return 0;
        }
    }`

Parso library, since version 2.0.3, starts to check using available() method before parsing input stream, this has caused failure in parsing SAS binary file.

**Comment by PetrTsurinov** [comment]
Removed using of available method, now just catching exception.
