### ISSUE TITLE
parso support for highly-parallel reads

### ISSUE THREAD

**Issue by Tagar** [epam/parso#21]
Would it be feasible to incorporate a small diff 
from https://github.com/saurfang/spark-sas7bdat/ project 
into Parso library?

The diff only touches `void readNextPage()` function:
see https://www.diffchecker.com/V6tGyqNC around lines 916-935.

This change allows sas7bdat files to be readable in highly-parallel fashion using multiple threads.
Basically, sas7bdat files would be "splittable" (Hadoop terminology).

(splittability would only apply to reading uncompressed files; 
this change does *not* break reading compressed files though)

We decided to bounce at you if this is feasible before creating a Pull Request.

**Comment by printsev** [comment]
Hey Ruslan, I believe these changes are already incorporated into the latest parso version. Could you please check if it is OK for you? We added some changes from this version a year ago or so. Please note that we have not incorporated some changes around read vs readFully deliberately as it might break reading somewhat broken sas7bdat files.

**Comment by Tagar** [comment]
Thank you @printsev - got it.
