### ISSUE TITLE
Export column formats

### ISSUE THREAD

**Issue by tangxuan82** [epam/parso#22]
Hi All,
     Currently, I have some troubles to export the column formats. For columns with character and non-date-time number,  no column format  is exported. For columns with date-time number, the column format is incomplete with only letters like "DATETIME" .

  Could you please help with this?

Kind regards,

Jiaowei

**Comment by m00nwlkr** [comment]
I have observed the same behavior as the original poster. What seems to happen is that none of the SAS format width/precision information is extracted from the sas metadata. Here are a few examples:
  format in sas: $12.    column format in parso: $.
  format in sas: 7.4     column format in parso: null
  format in sas: BEST12.      column format in parso: BEST.
  format in sas: MMDDYY10.      column format in parso: MMDDYY.

Below is a link to some public sas7bdat files that contain sas formats. You can see that parso is not able to retrieve format width and precision information as stated in the original post.
https://www.st.nmfs.noaa.gov/st1/recreational/MRIP_Survey_Data/SAS/

**Comment by printsev** [comment]
ok, thanks. looks like similar issue was reported in google groups as well. we will take a look at it.
