### ISSUE TITLE
Can't find 2.0.8 version in Maven central repo

### ISSUE THREAD

**Issue by mulya** [epam/parso#25]
Hello guys, I want to use your new 2.0.8 version as a dependency but can't find it in Maven central repo? Did you publish it already?

**Comment by printsev** [comment]
Thanks for reminder. We have published the snapshot, and we will publish the release early next week. For now, please use 2.0.8-SNAPSHOT: https://oss.sonatype.org/content/repositories/snapshots/com/epam/parso/2.0.8-SNAPSHOT/

**Comment by mulya** [comment]
Ok, thanks. Lets leave this issue open and close it when you publish the release

**Comment by printsev** [comment]
Done
