### ISSUE TITLE
Version tagging

### ISSUE THREAD

**Issue by aborg0** [epam/parso#3]
It would be nice if the published versions of the sources were tagged and pushed to the github repository too (as releases, probably the binaries/sources also available as a download). (Currently that would be only `2.0`.)

**Comment by printsev** [comment]
I don't think we can publish GGA sources as EPAM... So 1.2.1 sources are available in maven central and will always be there. What do you think?

**Comment by printsev** [comment]
Or do you mean just the tag of the 2.0 version in central? Good point, I agree, we will do it of course.

**Comment by aborg0** [comment]
Yeah, only for 2.0.

**Comment by PetrTsurinov** [comment]
Added tag "v2.0".
