### ISSUE TITLE
Wrong format for "weekday" when writing CSV

### ISSUE THREAD

**Issue by xizhu-mstr-2** [epam/parso#32]
The format for "WEEKDAY" in parso is 'F' but actually by definition from sas it should be 'u'. 
This is the related code in DataWriterUtil.java: put("WEEKDAY", "F");

This is the description from sas about "weekday" format:
The WEEKDAYw. format writes a SAS date value as the day of the week (where 1=Sunday, 2=Monday, and so on).

Here is the description of 'F' and 'u' from SimpleDateFormat:

F    Day of week in month

u    Day number of week (1 = Monday, ..., 7 = Sunday)

As a result, we should use 'u' as the format for weekday.

**Comment by printsev** [comment]
Thanks for finding this!
