### ISSUE TITLE
Make the SasFileParser() API Public

### ISSUE THREAD

**Issue by thesuperzapper** [epam/parso#51]
Hi Guys, I am the maintainer of the [spark-sas7bdat package](https://github.com/saurfang/spark-sas7bdat), which is used by many to read large SAS7BDAT with Apache Spark across many servers.

The issue is, because we need to start reading arbitrary offsets of the sas files (so each of the servers only reads a piece of the file), we need to call some of the protected methods/constructors in Parso.

Currently we use this crazy hack ([PrivateMethodExposer.scala](https://github.com/saurfang/spark-sas7bdat/blob/v2.1.0/src/main/scala/com/github/saurfang/sas/util/PrivateMethodExposer.scala))   to break the into protected methods and constructors. 

I would love it if you could publicly expose the following things:
1. The constructor for `com.epam.parso.impl.SasFileParser`
1. The `getSasFileProperties()` method of `SasFileParser`
1. The `readNext()` method of `SasFileParser`
1. The `readNextPage()` method of `SasFileParser`
1. The constants: `TIME_FORMAT_STRINGS`, `DATE_FORMAT_STRINGS`, and `EPSILON`

Here is the actual class we use in conjunction with the PrivateMethodExposer.scala, so we can use `com.epam.parso.impl.SasFileParser`: [ParsoWrapper.scala](https://github.com/saurfang/spark-sas7bdat/blob/v2.1.0/src/main/scala/com/github/saurfang/sas/parso/ParsoWrapper.scala)

**Comment by printsev** [comment]
Hi Mathew, 

Thanks for sharing your issue. Could you please answer the following questions so we can find out the best way to help you.

1. Would it be possible for you to use SasFileReaderImpl?
2. Why do you need `readNextPage()` to be public as this is internal method for file parsing?

Thanks

**Comment by thesuperzapper** [comment]
@printsev 
This is the process we currently use to distribute the reading of sas files across multiple servers: 
1. Each worker is provided a rough "start point" and "end point" in byte offsets from the beginning of the file. (These are coordinated by a master node and have roughly "File Size"/"Num workers" bytes)
1. Each worker initialises a `com.epam.parso.impl.SasFileParser`. 
    1. With the input stream starting from byte 0, so that it can read the metadata in the header.
1. Each worker moves its "start point" and  "end point" backwards such that they sit on the closest preceding page end.
1. Each worker seeks the SasFileParser's input stream to the "start point" 
    1. After this we call [readNextPage()](https://github.com/saurfang/spark-sas7bdat/blob/v2.1.0/src/main/scala/com/github/saurfang/sas/mapreduce/SasRecordReader.scala#L118) so that the internals of Parso get reset to the new offset.
  1. Each worker reads new rows until the input stream is at "end point" offset.

[Here is the code](https://github.com/saurfang/spark-sas7bdat/blob/v2.1.0/src/main/scala/com/github/saurfang/sas/mapreduce/SasRecordReader.scala#L34), which currently uses hacks to expose the private methods described above.

**Comment by Yana-Guseva** [comment]
Hi @thesuperzapper,

Will you be comfortable if we provide public access to readNextPage() method via SasFileReaderImpl class? This class already contains public access methods to getSasFileProperties() and readNextPage() which you use in your code. Constants like TIME_FORMAT_STRINGS, DATE_FORMAT_STRINGS, and EPSILON was moved to public interfaces (will soon be released), in this way it looks like we can add `public void readNextPage()` method to SasFileReaderImpl and you can use it instead of creating instance of SasFileParser directly. Or there are any other reasons why you need instance of SasFileParser class? Thank you.

**Comment by thesuperzapper** [comment]
@Yana-Guseva That would probably work.

**Comment by thesuperzapper** [comment]
@Yana-Guseva any progress on this? 
We would love to make spark-sas7bdat use this new public API.

**Comment by Yana-Guseva** [comment]
@thesuperzapper currently all changes related to this issue are available in the master branch. Please let me know if you run into any problems.

**Comment by thesuperzapper** [comment]
@Yana-Guseva @printsev While these changes are now in the master branch, no release has happened in many months. 

When are you planning to cut a release with these changes? (the `spark-sas7bdat` package needs this change urgently to support Spark 3.0)

**Comment by Tagar** [comment]
@printsev @Yana-Guseva any chance a new release can be cut from master? thx!!

**Comment by printsev** [comment]
Sorry for some delay with my answer -- vacation time (even the year is absolutely crazy). I've deployed 2.0.12-SNAPSHOT to maven snapshot. Hope it's OK for now, and after we deal with some failing tests (I believe it's not the application as they are failing even with code from 2016), we can make a 2.0.12 release. Hope it's OK.

**Comment by Tagar** [comment]
Thank you Igor

**Comment by printsev** [comment]
I've made the 2.0.12 release, please let me know if it works for you
