### ISSUE TITLE
Dates returned as integers

### ISSUE THREAD

**Issue by luca-vercelli** [epam/parso#65]
Why does this library return dates as `java.lang.Number`'s and not as `java.util.Date`?
I know that SAS dates are in facts integers, however in Java these are quite useless.
Maybe you can add some note in docs about how to convert Number's to Date's ?

**Edit**: dates are returned as `java.util.Date` if and only if their column format is the standard one, "DDMMYY10.", other formats are returned as `java.lang.Number` !!!

**Comment by printsev** [comment]
It should be returning dates, check bytesToDate and bytesToTime in https://github.com/epam/parso/blob/master/src/main/java/com/epam/parso/impl/SasFileParser.java

**Comment by printsev** [comment]
list of supported formats is here: https://github.com/epam/parso/blob/master/src/main/java/com/epam/parso/impl/DateTimeConstants.java

Could you please share the file you experience issues with?

**Comment by luca-vercelli** [comment]
You can try [this](https://uploadify.net/119d1550ada18c0a/migr_co_ft_st1_2.sas7bdat)

**Comment by printsev** [comment]
I was just about to get back to this, but I cannot find the file anymore. Could you please re-upload it?

**Comment by luca-vercelli** [comment]
I have upldated the link above

**Comment by printsev** [comment]
Thanks. I might be missing something but I am able to see java.util.Date in this file, please find the test I used below. The date format in this file is "YYMMDD8N." which is supported in DateTimeConstants.DATE_FORMAT_STRINGS (line 87).

`@Test
    public void testDateFormat() throws Exception {
        try (InputStream is = Files.newInputStream(Paths.get(this.getClass().getResource(
                "/bugs/migr_co_ft_st1_2.sas7bdat").toURI()))) {
            SasFileReader sasFileReader = new SasFileReaderImpl(is);
            Object[][] fileContents = sasFileReader.readAll();
            List<Column> columnsList = sasFileReader.getColumns();
            org.fest.assertions.Assertions.assertThat(fileContents[0][11]).isInstanceOf(java.util.Date.class);
            org.fest.assertions.Assertions.assertThat(fileContents[0][0]).isInstanceOf(java.util.Date.class);
        }
    }`

**Comment by luca-vercelli** [comment]
I just run that test. And it fails!
Please notice that I am importing parso via maven:

  	<dependency>
  		<groupId>com.epam</groupId>
  		<artifactId>parso</artifactId>
  		<version>2.0</version>
  	</dependency>

maybe the bug has been solved after version 2.0?

**Comment by printsev** [comment]
I for sure think so! Please try the latest one, 2.0.12. 2.0 is way outdated!

**Comment by luca-vercelli** [comment]
With 2.0.12 tests succed. Thank you.
