### ISSUE TITLE
integration with github actions

### ISSUE THREAD

**Issue by printsev** [epam/parso#66]
- automatic builds after each commit
- publishing to sonatype
- publishing to maven central (https://blackdoor.github.io/blog/maven-cd/)

**Comment by MysterionRise** [comment]
@printsev let's better integrate with Github Actions instead?

**Comment by printsev** [comment]
yes, agree, it's much better!

**Comment by timazet** [comment]
Github Actions are used to establish CI.
Related Wiki page is created - https://github.com/epam/parso/wiki/Continuous-Integration
