### ISSUE TITLE
CSVDataWriterUnitTest fails in JDK9+

### ISSUE THREAD

**Issue by printsev** [epam/parso#71]
If we start using JDK9+, some tests would fail because "PM" and "AM" would be lowercase in UK locale (https://bugs.openjdk.java.net/browse/JDK-8211985 for details). So either we need to change the locale in SasFileReaderUnitTest to something else or need to make "AM" and "PM" lowercase in "date_formats.csv"

**Comment by MysterionRise** [comment]
@printsev exactly the problem i encountered during my tries to run Parso on JDK 14
