### ISSUE TITLE
Row count zero

### ISSUE THREAD

**Issue by ruiwanguk** [epam/parso#9]
Using version 2.0 to parse sas7bdat file, the file version is 9.0401M3 and the server type is X64_S08R2. However, the row count in SasFileProperties shows zero (should have 729 rows). 

The file can be loaded in SAS Universal viewer. 

Any suggestions?

**Comment by FriedEgg** [comment]
In SAS version 9.3 the EXTENDOBSCOUNTER= option was added to data-step and libname, default=no
In SAS version 9.4 the EXTENDOBSCOUNTER= options was additionally available as a system option, default=yes

According to the [SAS documentation](http://support.sas.com/documentation/cdl/en/ledsoptsref/68025/HTML/default/viewer.htm#p1jhs9wvl8xi7vn1u8r4tmlxaqi7.htm)

> [EXTENDOBSCOUNTER=YES] requests an enhanced file format in a newly created SAS data file that counts observations beyond the 32-bit limitation. Although this SAS data file is created for an operating environment that stores the number of observations with a 32-bit integer, the data file behaves like a 64-bit file with respect to counters. This is the default.
> Restrictions	A SAS data file that is created with an extended observation count is incompatible with releases prior to SAS 9.3.

That all being said, Parso, to my knowledge, already supports this.  I attempted to duplicate my assumption of the problem to no avail.

@ruiwanguk Will you try using the files attached and see if you can replicate your issue?
[resources.zip](https://github.com/epam/parso/files/509933/resources.zip)

```sas
%macro make_it(extend);
data extend_yes(extendobscounter=&extend.);
length id 8;
array num[0:9];
do id=1 to 729;
do _n_=0 to 9 by 1;
num[_n_]=ranuni(1234);
end;
output;
end;
run;
%mend;
%make_it(no)
%make_it(yes)
```

```java
    public static void main(String[] args) {
        File initialFile = new File("src/main/resources/extend_yes.sas7bdat");
        try {
            InputStream is = new FileInputStream(initialFile);
            SasFileReader sasFileReader = new SasFileReaderImpl(is);
            SasFileProperties sasFileProperties = sasFileReader.getSasFileProperties();
            System.out.println(sasFileProperties.getName() + " has " + sasFileProperties.getRowCount() + " rows");
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }

    }
```

```
EXTEND_YES has 729 rows
```

**Comment by FriedEgg** [comment]
I was able to replicate the issue by created an EXTENDOBSCOUNTER=YES file with a U64 Data Representation (SOLARIS_64).  The row count=0, with EXTENDOBSCOUNTER=YES and prints correctly when EXTENDOBSCOUNTER=NO

I have attached example sas7bdat files.

[resources.zip](https://github.com/epam/parso/files/509959/resources.zip)

**Comment by ruiwanguk** [comment]
@FriedEgg thanks a lot for the prompt answer. I did a quick test on the two files you shared. 'extend_no' works as expected, the row count is correct. However, as you said, the row count for 'extend_yes' is zero. 

On thing I'd like to add is that, in our SAS file, U64 was false and endianness was 1. Would this affect things? 

Also, I am wondering what the best way is going forward. Is this something that can be easily fixed?

**Comment by FriedEgg** [comment]
@ruiwanguk Some additional information about your file would be helpful.  Are you aware of the encoding used?

I tried every option available for data representation and can only get OBS= 0 returned when U64 is true and endianness is 0

```
no_alpha_tru64,     OBS= 19, isU64= true,  endianness= 1
no_alpha_vms_32,    OBS= 19, isU64= false, endianness= 1
no_alpha_vms_64,    OBS= 19, isU64= false, endianness= 1
no_hp_ux_32,        OBS= 19, isU64= false, endianness= 0
no_intel_abi,       OBS= 19, isU64= false, endianness= 1
no_linux_ia64,      OBS= 19, isU64= true,  endianness= 1
no_linux_x86_64,    OBS= 19, isU64= true,  endianness= 1
no_mips_abi,        OBS= 19, isU64= false, endianness= 0
no_mvs_32,          OBS= 19, isU64= false, endianness= 0
no_os2,             OBS= 19, isU64= false, endianness= 1
no_rs_6000_aix_32,  OBS= 19, isU64= false, endianness= 0
no_solaris_32,      OBS= 19, isU64= false, endianness= 0
no_solaris_x86_64,  OBS= 19, isU64= true,  endianness= 1
no_vax_vms,         OBS= 19, isU64= false, endianness= 1
no_vms_ia64,        OBS= 19, isU64= false, endianness= 1
no_windows_32,      OBS= 19, isU64= false, endianness= 1
no_windows_64,      OBS= 19, isU64= false, endianness= 1
yes_alpha_tru64,    OBS= 19, isU64= true,  endianness= 1
yes_alpha_vms_32,   OBS= 19, isU64= false, endianness= 1
yes_alpha_vms_64,   OBS= 19, isU64= false, endianness= 1
yes_hp_ux_32,       OBS= 19, isU64= false, endianness= 0
yes_intel_abi,      OBS= 19, isU64= false, endianness= 1
yes_linux_ia64,     OBS= 19, isU64= true,  endianness= 1
yes_linux_x86_64,   OBS= 19, isU64= true,  endianness= 1
yes_mips_abi,       OBS= 19, isU64= false, endianness= 0
yes_mvs_32,         OBS= 19, isU64= false, endianness= 0
yes_os2,            OBS= 19, isU64= false, endianness= 1
yes_rs_6000_aix_32, OBS= 19, isU64= false, endianness= 0
yes_solaris_32,     OBS= 19, isU64= false, endianness= 0
yes_solaris_x86_64, OBS= 19, isU64= true,  endianness= 1
yes_vax_vms,        OBS= 19, isU64= false, endianness= 1
yes_vms_ia64,       OBS= 19, isU64= false, endianness= 1
yes_windows_32,     OBS= 19, isU64= false, endianness= 1
yes_windows_64,     OBS= 19, isU64= false, endianness= 1

no_hp_ia64,         OBS= 0,  isU64= true,  endianness= 0
no_hp_ux_64,        OBS= 0,  isU64= true,  endianness= 0
no_mvs_64_bfp,      OBS= 0,  isU64= true,  endianness= 0
no_rs_6000_aix_64,  OBS= 0,  isU64= true,  endianness= 0
no_solaris_64,      OBS= 0,  isU64= true,  endianness= 0
yes_hp_ia64,        OBS= 0,  isU64= true,  endianness= 0
yes_hp_ux_64,       OBS= 0,  isU64= true,  endianness= 0
yes_mvs_64_bfp,     OBS= 0,  isU64= true,  endianness= 0
yes_rs_6000_aix_64, OBS= 0,  isU64= true,  endianness= 0
yes_solaris_64,     OBS= 0,  isU64= true,  endianness= 0
```

additionally, the extendobscounter option doesn't appear to have anything to do with the issue.  the extend_no file I shared yesterday was incorrect.

**Comment by ruiwanguk** [comment]
@FriedEgg Thank you. How do I find out the encoding of the SAS file? I am afraid I don't have a SAS installed locally. 

Some additional information: 

- compressionMethod; SASYZCRL
- fileType: DATA

**Comment by FriedEgg** [comment]
Please provide the hex values from bytes 70-72 of your file.  These bytes provide the information for Character Encoding, parso does not currently appear to have a method to support this.

**Comment by PetrTsurinov** [comment]
@FriedEgg Thank you for file examples and for information about Character Encoding storing, that's really helpful. If you have any additional information about sas7bdat metadata storing which parso doesn't support we would appreciate that. Please feel free to create merge requests.
@ruiwanguk Please try updated parso code on your file, we created fix for described issue. If it does I think the issue can be closed.

**Comment by PetrTsurinov** [comment]
Got information from @ruiwanguk : "Version 2.0.2 has passed my local tests, you can close this ticket now.".
